// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * Migrations e introspecção do Prisma só funcionam contra um arquivo SQLite
 * local — o schema engine não migra direto no Turso (libsql://). Por isso os
 * comandos de CLI (`prisma migrate dev`, etc.) sempre usam o banco local.
 *
 * Para aplicar as migrations no staging/produção, use os scripts:
 *   npm run db:deploy:staging
 *   npm run db:deploy:production
 */
export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    url:
      process.env["LOCAL_DATABASE_URL"] ??
      process.env["DATABASE_URL"] ??
      "file:./dev.db",
  },
});
