export const exchangeDetailInclude = {
  items: true,
  shippings: true,
  events: { orderBy: { createdAt: "asc" as const } },
  openedBy: { select: { id: true, name: true } },
  order: {
    select: {
      id: true,
      orderNumber: true,
      status: true,
      email: true,
      phone: true,
      recipientName: true,
      destinationCep: true,
      addressStreet: true,
      addressNumber: true,
      addressComplement: true,
      addressNeighborhood: true,
      addressCity: true,
      addressState: true,
      cpf: true,
      paidAt: true,
      deliveredAt: true,
      shippingStatus: true,
      fulfillmentType: true,
      shippingServiceName: true,
      deliveryNotes: true,
      shippingAmount: true,
      total: true,
      items: {
        select: {
          id: true,
          productId: true,
          productName: true,
          productImageUrl: true,
          quantity: true,
          price: true,
          pieceSelectionsJson: true,
        },
      },
    },
  },
} as const;
